name: build-notify-send_telegram

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Display the path
        run: |
          env && echo "Working dir:$( pwd)" && echo "dir ls: $( ls -l )" && echo "tree: $( tree )"
        shell: bash

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "notify/send_telegram/"
          file: "notify/send_telegram/Dockerfile"
          tags: "haumdaucherdatalab/kubeflow_send_telegram:latest"
          platforms: "linux/arm64,linux/amd64"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
